#!/usr/bin/env python3
"""
AI Agent-Aided Research System — Project Setup

Interactive or CLI-driven project initialization. Seeds all working documents
(plan, progress, references, plotting utilities, consensus memory) and
optionally runs the Director and Librarian agents before launching the watcher.

Usage:
    python setup.py --name "My Paper" --journal "Nature Energy" --topic "..." ...
    python setup.py --from-file seed.json
    python setup.py                      # interactive mode
"""

import argparse
import json
import os
import subprocess
import sys
import textwrap
import time
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent

PLAN_TEMPLATE = """\
# Research Plan

_Generated by setup.py on {date}_

---

## User Input

| Field               | Value |
|---------------------|-------|
| **Paper Name**      | {name} |
| **Target Journal**  | {journal} |
| **Topic**           | {topic} |
| **Data**            | {data} |
| **Methods**         | {methods} |
| **Research Gap**    | {gap} |
| **Target Contribution** | {contribution} |
| **Additional Context** | {additional_context} |

---

## Director: Research Strategy

_To be filled by the Director agent._

### Research Question
[One clear sentence a non-specialist can understand]

### Novelty Statement
[1-2 sentences. What insight exists after this paper that did not exist before?]

### Why It Works
[The mechanism/theory/insight — not just "we apply X to Y"]

### Narrative Arc
1. Gap: [What is missing?]
2. Insight: [What key idea closes this gap?]
3. Evidence: [What experiments prove the insight?]
4. Impact: [What changes because of this work?]

### Target Journal
{journal} — [Rationale to be filled by Director]

### Publishability Assessment
[Honest 1-10 rating with justification]

### Experiment Contract (Suggested)
[Concrete experiments, expected outputs, success criteria]

---

## Librarian: Literature Review

_To be filled by the Librarian agent._

### Key Papers
[List of 15-30 most relevant papers with short annotations]

### Literature Gap Analysis
[What the literature covers well, what is genuinely missing]

### Citation Graph
[Key clusters of related work and how this paper fits]

### FIGURE_QUALITY_STANDARDS
[Analysis of competitor figures — styles, color schemes, layouts]

---

## Paper Outline

_To be filled after Director and Librarian complete their sections._

### Structure
1. Introduction
2. Methodology
3. Results
4. Discussion
5. Conclusion

### Section Assignments
[Estimated page counts, key points per section]

---

## Experiment Contract

_Finalized after Director review._

| # | Experiment | Expected Output | Success Criteria |
|---|-----------|-----------------|------------------|
| 1 | TBD       | TBD             | TBD              |

---

## Writing Schedule

| Phase | Focus | Estimated Cycles |
|-------|-------|-----------------|
| 1     | Literature + Direction | 1 |
| 2     | Core methodology + initial results | 3-5 |
| 3     | Full results + figures | 5-10 |
| 4     | Writing + polish | 5-10 |
| 5     | Final review convergence | 3-5 |
"""

PROGRESS_TEMPLATE = """\
# Progress Log

_Last updated: {date}_

## Status: INITIALIZED

### Completed
- [x] Project setup complete

### In Progress
- [ ] Director agent: research strategy
- [ ] Librarian agent: literature review

### Blocked
- (none)

### Notes
Project initialized on {date}.
"""

BIB_TEMPLATE = """\
% references.bib — generated by setup.py
% Add references below. The Librarian agent will populate this file.

"""

PLOTTING_UTILS = '''\
#!/usr/bin/env python3
"""
Shared plotting utilities for journal-quality figures.

Provides consistent color schemes, line styles, marker sets, and
helper functions for publication-ready matplotlib figures.

Usage:
    from utils.plotting_utils import setup_style, save_figure, COLORS, LINES, MARKERS
    setup_style()
    fig, ax = plt.subplots()
    ax.plot(x, y, color=COLORS["model"], linestyle=LINES["solid"], marker=MARKERS["circle"])
    save_figure(fig, "my_figure")
"""

import warnings
from pathlib import Path

try:
    import matplotlib
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
    from matplotlib.colors import LinearSegmentedColormap
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    warnings.warn(
        "matplotlib not installed. Install with: pip install matplotlib>=3.7",
        stacklevel=2,
    )

try:
    import numpy as np
    HAS_NP = True
except ImportError:
    HAS_NP = False


# ---------------------------------------------------------------------------
# Color palette — colorblind-safe, print-friendly
# ---------------------------------------------------------------------------

COLORS = {
    # Primary results
    "dns":        "#1b9e77",   # teal-green — ground truth / reference data
    "model":      "#d95f02",   # orange — proposed method
    # Baselines for comparison
    "baseline1":  "#7570b3",   # muted purple
    "baseline2":  "#e7298a",   # magenta-pink
    "baseline3":  "#66a61e",   # olive green
    # Experimental data
    "experiment": "#e6ab02",   # gold-yellow
    # Utility
    "grid":       "#cccccc",
    "text":       "#333333",
    "highlight":  "#a6761d",   # brown for annotations
}

# Sequential palette for multi-series plots
PALETTE_SEQ = [
    COLORS["model"],
    COLORS["dns"],
    COLORS["baseline1"],
    COLORS["baseline2"],
    COLORS["baseline3"],
    COLORS["experiment"],
    COLORS["highlight"],
]

# ---------------------------------------------------------------------------
# Line styles
# ---------------------------------------------------------------------------

LINES = {
    "solid":    "-",
    "dashed":   "--",
    "dotted":   ":",
    "dashdot":  "-.",
}

LINE_CYCLE = ["-", "--", ":", "-."]

# ---------------------------------------------------------------------------
# Marker styles
# ---------------------------------------------------------------------------

MARKERS = {
    "circle":   "o",
    "square":   "s",
    "triangle": "^",
    "diamond":  "D",
    "star":     "*",
    "cross":    "x",
    "plus":     "+",
    "pentagon":  "p",
}

MARKER_CYCLE = ["o", "s", "^", "D", "*", "x", "+", "p"]


# ---------------------------------------------------------------------------
# Style setup
# ---------------------------------------------------------------------------

def setup_style(
    font_size: int = 10,
    fig_width_inches: float = 3.5,
    aspect_ratio: float = 0.75,
    use_tex: bool = False,
    dpi: int = 300,
):
    """
    Configure matplotlib for journal-quality figures.

    Parameters
    ----------
    font_size : int
        Base font size (default 10 pt, standard for most journals).
    fig_width_inches : float
        Figure width. Common values:
        - 3.5  = single column
        - 5.5  = 1.5 column
        - 7.0  = full page width
    aspect_ratio : float
        Height / width ratio (default 0.75).
    use_tex : bool
        If True, use LaTeX rendering (requires texlive).
    dpi : int
        Resolution for raster output.
    """
    if not HAS_MPL:
        return

    fig_height = fig_width_inches * aspect_ratio

    plt.rcParams.update({
        # Font
        "font.family": "serif" if use_tex else "DejaVu Serif",
        "font.size": font_size,
        "text.usetex": use_tex,

        # Figure
        "figure.figsize": (fig_width_inches, fig_height),
        "figure.dpi": dpi,
        "savefig.dpi": dpi,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,

        # Axes
        "axes.labelsize": font_size,
        "axes.titlesize": font_size + 1,
        "axes.linewidth": 0.6,
        "axes.grid": True,
        "axes.grid.which": "major",
        "axes.spines.top": False,
        "axes.spines.right": False,

        # Grid
        "grid.alpha": 0.3,
        "grid.linewidth": 0.4,

        # Ticks
        "xtick.labelsize": font_size - 1,
        "ytick.labelsize": font_size - 1,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.major.width": 0.5,
        "ytick.major.width": 0.5,
        "xtick.minor.visible": True,
        "ytick.minor.visible": True,

        # Lines
        "lines.linewidth": 1.2,
        "lines.markersize": 4,

        # Legend
        "legend.fontsize": font_size - 1,
        "legend.frameon": False,
        "legend.handlelength": 1.5,
    })


def save_figure(
    fig,
    name: str,
    output_dir: str | Path | None = None,
    formats: tuple[str, ...] = ("pdf", "png"),
    dpi: int = 300,
    transparent: bool = False,
):
    """
    Save a figure in multiple formats for paper inclusion.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
        The figure to save.
    name : str
        Base filename (without extension).
    output_dir : str or Path, optional
        Directory to save into. Defaults to paper/figures/.
    formats : tuple of str
        Output formats (default: PDF for LaTeX, PNG for preview).
    dpi : int
        Resolution for raster formats.
    transparent : bool
        Transparent background.
    """
    if output_dir is None:
        # Default: paper/figures/ relative to repo root
        output_dir = Path(__file__).resolve().parent.parent.parent / "paper" / "figures"

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for fmt in formats:
        path = output_dir / f"{name}.{fmt}"
        fig.savefig(
            path,
            format=fmt,
            dpi=dpi,
            bbox_inches="tight",
            pad_inches=0.02,
            transparent=transparent,
        )
    plt.close(fig)


def get_color_cycle(n: int) -> list[str]:
    """Return n distinct colors from the sequential palette."""
    if n <= len(PALETTE_SEQ):
        return PALETTE_SEQ[:n]
    # Repeat if needed
    return [PALETTE_SEQ[i % len(PALETTE_SEQ)] for i in range(n)]


def annotate_point(
    ax, text: str, xy: tuple, offset: tuple = (10, 10), **kwargs
):
    """Add a clean annotation arrow to a data point."""
    defaults = dict(
        fontsize=8,
        arrowprops=dict(arrowstyle="->", color=COLORS["text"], lw=0.6),
        color=COLORS["text"],
        ha="left",
    )
    defaults.update(kwargs)
    ax.annotate(text, xy=xy, xytext=offset, textcoords="offset points", **defaults)
'''

CONSENSUS_TEMPLATE = """\
# Consensus Memory

_Shared knowledge base across all agents. Updated by agents as the project evolves._

## Project Identity
- **Paper Name**: {name}
- **Target Journal**: {journal}
- **Initialized**: {date}

## Agreed Facts
- (populated during research)

## Open Questions
- (populated during research)

## Design Decisions
- (populated during research)

## Key Findings
- (populated during research)
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def ask(prompt: str, default: str = "") -> str:
    """Prompt the user interactively; return default if empty."""
    suffix = f" [{default}]" if default else ""
    answer = input(f"{prompt}{suffix}: ").strip()
    return answer if answer else default


def seed_file(path: Path, content: str, overwrite: bool = False):
    """Write content to path, creating parent dirs. Skip if exists unless overwrite."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        print(f"  [skip] {path.relative_to(ROOT)} (already exists)")
        return
    path.write_text(content, encoding="utf-8")
    print(f"  [seed] {path.relative_to(ROOT)}")


def run_agent(role: str, prompt: str, timeout_min: int, model: str = "claude-opus-4-6"):
    """
    Run a Claude agent via the CLI.

    Returns (success: bool, elapsed_sec: float).
    """
    cmd = [
        "claude",
        "--dangerously-skip-permissions",
        "--output-format", "stream-json",
        "--verbose",
        "--max-turns", "50",
        "--model", model,
        "-p", prompt,
    ]

    print(f"\n{'='*60}")
    print(f"  Running {role} agent (timeout: {timeout_min} min, model: {model})")
    print(f"{'='*60}\n")

    start = time.time()
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(ROOT),
            timeout=timeout_min * 60,
            capture_output=True,
            text=True,
        )
        elapsed = time.time() - start
        if proc.returncode == 0:
            print(f"  {role} completed in {elapsed:.0f}s")
            return True, elapsed
        else:
            print(f"  {role} exited with code {proc.returncode} after {elapsed:.0f}s")
            if proc.stderr:
                # Print last few lines of stderr for diagnostics
                for line in proc.stderr.strip().splitlines()[-5:]:
                    print(f"    stderr: {line}")
            return False, elapsed
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        print(f"  {role} timed out after {elapsed:.0f}s")
        return False, elapsed
    except FileNotFoundError:
        print("  ERROR: 'claude' CLI not found. Is it installed and on PATH?")
        return False, 0.0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Initialize the AI Agent-Aided Research System",
    )
    parser.add_argument("--name", help="Paper name / short title")
    parser.add_argument("--journal", help="Target journal")
    parser.add_argument("--topic", help="Research topic description")
    parser.add_argument("--data", help="Available data description")
    parser.add_argument("--methods", help="Proposed methods")
    parser.add_argument("--gap", help="Research gap to address")
    parser.add_argument("--target-contribution", dest="contribution",
                        help="Intended contribution")
    parser.add_argument("--additional-context", dest="additional_context",
                        default="", help="Any extra context for agents")
    parser.add_argument("--from-file", dest="from_file",
                        help="Load seed values from a JSON file")
    parser.add_argument("--skip-agents", action="store_true",
                        help="Skip Director and Librarian agents")
    parser.add_argument("--no-start", action="store_true",
                        help="Do not auto-start watcher.py after setup")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite existing seed files")
    args = parser.parse_args()

    print("\n" + "=" * 60)
    print("  AI Agent-Aided Research System — Project Setup")
    print("=" * 60 + "\n")

    # --- Gather inputs -------------------------------------------------
    if args.from_file:
        path = Path(args.from_file)
        if not path.exists():
            print(f"ERROR: Seed file not found: {path}")
            sys.exit(1)
        with open(path) as f:
            seed = json.load(f)
        name = seed.get("name", "Untitled")
        journal = seed.get("journal", "")
        topic = seed.get("topic", "")
        data = seed.get("data", "")
        methods = seed.get("methods", "")
        gap = seed.get("gap", "")
        contribution = seed.get("contribution", "")
        additional_context = seed.get("additional_context", "")
    elif args.name:
        # CLI mode — all from flags
        name = args.name
        journal = args.journal or ""
        topic = args.topic or ""
        data = args.data or ""
        methods = args.methods or ""
        gap = args.gap or ""
        contribution = args.contribution or ""
        additional_context = args.additional_context or ""
    else:
        # Interactive mode
        print("Enter project details (press Enter to skip optional fields):\n")
        name = ask("Paper name / short title")
        journal = ask("Target journal")
        topic = ask("Research topic")
        data = ask("Available data")
        methods = ask("Proposed methods")
        gap = ask("Research gap")
        contribution = ask("Target contribution")
        additional_context = ask("Additional context", "")

    if not name:
        print("ERROR: Paper name is required.")
        sys.exit(1)

    date = datetime.now().strftime("%Y-%m-%d %H:%M")

    # --- Seed files ----------------------------------------------------
    print("\nSeeding project files...\n")

    seed_file(
        ROOT / "work-progress" / "plan.md",
        PLAN_TEMPLATE.format(
            date=date, name=name, journal=journal, topic=topic,
            data=data, methods=methods, gap=gap,
            contribution=contribution, additional_context=additional_context,
        ),
        overwrite=args.overwrite,
    )

    seed_file(
        ROOT / "work-progress" / "progress.md",
        PROGRESS_TEMPLATE.format(date=date),
        overwrite=args.overwrite,
    )

    seed_file(
        ROOT / "paper" / "references.bib",
        BIB_TEMPLATE,
        overwrite=args.overwrite,
    )

    seed_file(
        ROOT / "code" / "utils" / "plotting_utils.py",
        PLOTTING_UTILS,
        overwrite=args.overwrite,
    )

    seed_file(
        ROOT / "memories" / "consensus.md",
        CONSENSUS_TEMPLATE.format(name=name, journal=journal, date=date),
        overwrite=args.overwrite,
    )

    # Save seed JSON for reproducibility
    seed_data = {
        "name": name,
        "journal": journal,
        "topic": topic,
        "data": data,
        "methods": methods,
        "gap": gap,
        "contribution": contribution,
        "additional_context": additional_context,
        "setup_date": date,
    }
    seed_file(
        ROOT / "paper_seed.json",
        json.dumps(seed_data, indent=2) + "\n",
        overwrite=args.overwrite,
    )

    print("\nProject files seeded successfully.\n")

    # --- Run agents ----------------------------------------------------
    if not args.skip_agents:
        # Director agent
        director_prompt = textwrap.dedent(f"""\
            You are the Director agent. Read CLAUDE.md for your full instructions
            and .claude/agents/director.md for your detailed persona.

            The user has provided the following research seed:
            - Paper Name: {name}
            - Target Journal: {journal}
            - Topic: {topic}
            - Available Data: {data}
            - Proposed Methods: {methods}
            - Research Gap: {gap}
            - Target Contribution: {contribution}
            - Additional Context: {additional_context}

            Your task:
            1. Read work-progress/plan.md
            2. Fill in the "Director: Research Strategy" section completely
            3. Be brutally honest about publishability
            4. Suggest a concrete Experiment Contract

            Write your output directly into work-progress/plan.md.
        """)
        ok, _ = run_agent("Director", director_prompt, timeout_min=20)
        if not ok:
            print("WARNING: Director agent did not complete successfully.")
            print("You can re-run it manually or continue with setup.\n")

        # Librarian agent
        librarian_prompt = textwrap.dedent(f"""\
            You are the Librarian agent. Read CLAUDE.md for your full instructions.

            Your persona: You channel Eugene Garfield — founder of citation indexing.
            You believe that understanding a field means understanding its citation
            structure. No paper exists in isolation.

            The project:
            - Paper Name: {name}
            - Target Journal: {journal}
            - Topic: {topic}
            - Research Gap: {gap}

            Your task:
            1. Read work-progress/plan.md (especially the Director section)
            2. Search for and identify the 15-30 most relevant papers
            3. Fill in the "Librarian: Literature Review" section of plan.md
            4. Populate paper/references.bib with properly formatted BibTeX entries
            5. Create related-papers/FIGURE_QUALITY_STANDARDS.md analyzing
               competitor figure styles for this journal
            6. Be thorough — missed key references will cause rejection

            Write your output directly into the appropriate files.
        """)
        ok, _ = run_agent("Librarian", librarian_prompt, timeout_min=30)
        if not ok:
            print("WARNING: Librarian agent did not complete successfully.")
            print("You can re-run it manually or continue.\n")
    else:
        print("Skipping Director and Librarian agents (--skip-agents).\n")

    # --- Optionally start watcher --------------------------------------
    if not args.no_start and not args.skip_agents:
        print("\n" + "-" * 60)
        answer = input("Start watcher.py now? [y/N]: ").strip().lower()
        if answer in ("y", "yes"):
            watcher_path = ROOT / "watcher.py"
            if watcher_path.exists():
                print(f"Starting watcher: python {watcher_path}")
                os.execvp(sys.executable, [sys.executable, str(watcher_path)])
            else:
                print(f"WARNING: {watcher_path} not found. Create it first.")
    elif args.no_start:
        print("Skipping watcher auto-start (--no-start).\n")

    print("\nSetup complete. Project is ready for the production loop.")
    print(f"  Plan:     work-progress/plan.md")
    print(f"  Progress: work-progress/progress.md")
    print(f"  Seed:     paper_seed.json")
    print(f"\nTo start the orchestrator: python watcher.py\n")


if __name__ == "__main__":
    main()
